In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
file_path = "C:\\Users\\sures\\OneDrive\\Documents\\Data Science\\Data Sets\\Salary_Data.csv"
df = pd.read_csv(file_path)
df

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [3]:
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [4]:
df.tail()

YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [5]:
df.isnull()

YearsExperience  Salary
0             False   False
1             False   False
2             False   False
3             False   False
4             False   False
5             False   False
6             False   False
7             False   False
8             False   False
9             False   False
10            False   False
11            False   False
12            False   False
13            False   False
14            False   False
15            False   False
16            False   False
17            False   False
18            False   False
19            False   False
20            False   False
21            False   False
22            False   False
23            False   False
24            False   False
25            False   False
26            False   False
27            False   False
28            False   False
29            False   False

In [6]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [7]:
df.dtypes

YearsExperience    float64
Salary             float64
dtype: object

In [8]:
df.shape

(30, 2)

In [9]:
df.columns

Index(['YearsExperience', 'Salary'], dtype='object')

We divide data into two parts i.e input data and output data

input data = X; output data=y

Again we divide input data into two parts i.e train and test

input train data= x_train; input test data= x_test

similarly we divide output data into two parts i.e train and test

output train data= y_train; output test data= y_test

Model development happens on train data i.e x_train and y_train

Model will predict by passing x_test data, these are called y_predictions

y_predictions will compare with y_test , this is called test accuracy/ test error

**Divide data into input and output data**

In [10]:
X = df[["YearsExperience"]]
y = df[["Salary"]]


**Divide data into train and test**

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,
                                                 y,
                                                 random_state=23,
                                                 test_size=0.2)


In [12]:
print(f"shape of df is : {df.shape}\
shape of X_train is : {X_train.shape}\
shape of X_test is : {X_test.shape}\
shape of y_train is : {y_train.shape}\
shape of y_test is : {y_test.shape}")

shape of df is : (30, 2)shape of X_train is : (24, 1)shape of X_test is : (6, 1)shape of y_train is : (24, 1)shape of y_test is : (6, 1)


In [13]:
y_train.shape,y_test.shape

((24, 1), (6, 1))

In [14]:
X_train

YearsExperience
24              8.7
1               1.3
3               2.0
26              9.5
17              5.3
18              5.9
0               1.1
14              4.5
5               2.9
11              4.0
2               1.5
25              9.0
23              8.2
28             10.3
29             10.5
7               3.2
12              4.0
13              4.1
27              9.6
22              7.9
9               3.7
8               3.2
6               3.0
19              6.0

**Model Development**

- Model development happens using train data
- X_train    y_train
- from sklearn.linear_model import LinearRegression
- LR=LinearRegression()


In [15]:
X_train.shape


(24, 1)

In [16]:
df.shape

(30, 2)

In [17]:
df.ndim   # number of dimensions

2

In [18]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(X_train,
       y_train)

LinearRegression()

**Model Predictions**

In [19]:
y_predictions = LR.predict(X_test)
y_predictions

array([[74501.41002938],
       [90279.63442954],
       [63363.83986457],
       [72645.14833525],
       [93064.02697075],
       [47585.61546441]])

**Model Evaluation**

In [20]:
from sklearn.metrics import r2_score,mean_squared_error

In [21]:
R2=r2_score(y_test,y_predictions)
MSE=mean_squared_error(y_test,y_predictions)
RMSE=np.sqrt(MSE)
#accuracy_score(y_test,y_predictions) # it is a regression tech
print("R-sqaure:",R2)
print("MSE:",MSE)
print("RMSE:",RMSE)

R-sqaure: 0.9184170849214232
MSE: 30404597.28731416
RMSE: 5514.036387920754


**Finding Coeffiecient and Intercept**
  - Coefficient means b0 ,b1 ,b2....

  - Coeffiecints depends on number of input features

  - In this data we have only one column as input i.e. Years of Experience

  - So we will get only one coeffiecnt

In [22]:
LR.coef_

array([[9281.30847068]])

In [23]:
LR.intercept_

array([27166.73682891])

- Regression_equation=LR.intercept_+LR.coef_*'YearsExperience'
- Regression_equation

**Save The Model**

In [34]:
import pickle
pickle.dump(LR,open("linear_salarydata.pkl","wb"))

**Load The Model**

In [35]:
model = pickle.load(open("linear_salarydata.pkl","rb"))
model

LinearRegression()

**Predictions**

In [26]:
X_test

YearsExperience
16              5.1
20              6.8
10              3.9
15              4.9
21              7.1
4               2.2

In [27]:
X_test.values

array([[5.1],
       [6.8],
       [3.9],
       [4.9],
       [7.1],
       [2.2]])

In [32]:
model.predict([[11]])

array([[129261.1300064]])

In [33]:
model.predict(X)

array([[ 37376.17614666],
       [ 39232.4378408 ],
       [ 41088.69953493],
       [ 45729.35377027],
       [ 47585.61546441],
       [ 54082.53139389],
       [ 55010.66224096],
       [ 56866.92393509],
       [ 56866.92393509],
       [ 61507.57817043],
       [ 63363.83986457],
       [ 64291.97071164],
       [ 64291.97071164],
       [ 65220.1015587 ],
       [ 68932.62494698],
       [ 72645.14833525],
       [ 74501.41002938],
       [ 76357.67172352],
       [ 81926.45680593],
       [ 82854.587653  ],
       [ 90279.63442954],
       [ 93064.02697075],
       [100489.07374729],
       [103273.4662885 ],
       [107914.12052384],
       [110698.51306504],
       [115339.16730038],
       [116267.29814745],
       [122764.21407692],
       [124620.47577106]])

In [30]:
import os
os.getcwd()

'C:\\Users\\sures\\OneDrive\\Documents\\Data Science\\Machine Learning'